### PR TITLE
fix(sass): Configure css modules with Gatsby #8

### LINKED ISSUE #8: CSS/Sass is not active
In the Playground, the Redliner components are way off, Sass is not being applied.

### PR DESCRIPTION
**Pull request by trybick**
Resolves #8 

The CSS for Redliner components was not being applied. This fixes the configuration of Sass with docz v2.

### CODE REVIEW

File: src/components/InfoBox/InfoBox.tsx [hunk 1]
```diff
@@ -1,7 +1,7 @@
 import * as React from 'react';
 import { Popper } from 'react-popper';
 
-import styles from '../RedLiner/RedLiner.scss'; // tslint:disable-line no-relative-imports
+import styles from '../RedLiner/RedLiner.module.scss';
```
Comment (trybick) [inline src/components/InfoBox/InfoBox.tsx:4]: This file extension is required for css modules in Gatbsy

File: src/declaration.d.ts [hunk 2]
```diff
@@ -0,0 +1 @@
+declare module '*.scss';
```
Comment (trybick) [inline src/declaration.d.ts:1]: Creating this file fixes linter errors on the `scss` import statements ("cannot find module" error)

**Comment by veiko** [comment]
Amazing, thanks @trybick!
